#  environment for linting document

## needs to be replaced with a general environment by maintainers

name: dashboard-lint
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pycodestyle
  - dash-bootstrap-components=1.2.0
  - dash=2.5.1
  - plotly-resampler=0.7.2.2
  - pip=20.2
  - waitress=2.1.2

